# -*- coding: utf-8 -*-
"""seenivasadharan python 5/6/2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bi80S8uTPCrRNSUJ8cKu7uRW3E3Yf-bw

1. Add Two Numbers
"""

a=10
b=5
print(a+b)

"""2. Subtract Two Numbers

"""

a=10
b=5
c=(a-b)
print(c)

"""3. Multiply Two Numbers

"""

a=10
b=5
c=a * b
print("Multiplication =", c)

"""4. Divide Two Numbers"""

a=10
b=5
print(a/b)

"""5. Find Remainder"""

a=10
b=3
print(a%b)

"""6. Find Square of a Number"""

num=5
square=num ** 2
print("Square =", square)

"""7. Find Cube of a Number"""

num=5
cube=num**3
print(cube)

"""8. Calculate Area of Rectangle"""

l=10
b=5
print(l*b)

"""9. Calculate Area of Circle"""

r=7
p=3.14159
area=7*3.14159**2
print(area)

"""10. Calculate Simple Interest

Formula: SI = (P × R × T) / 100
"""

p=10000
r=5
t=2
si=(p*r*t)/100
print(si)

"""11. Calculate Compound Interest

Formula: CI = P(1 + R/100)^T - P
"""

p=10000
r=5
t=2
ci=p*(1+r/100)**t-p
print(ci)

"""12. Calculate Average Marks"""

m1=80
m2=75
m3=90
avg=(m1+m2+m3)/3
print("avg=",avg)

"""13. Calculate Profit

Formula: Profit = Selling Price − Cost Price
"""

cp=500
sp=700
profit=(sp-cp)
print("profit=",profit)

"""14. Calculate Loss profit

Formula: Loss = Cost Price − Selling Price
"""

cp=700
sp=500
loss=(cp-sp)
print("loss=",loss)

"""15. Calculate Monthly Savings

Formula: Savings = Income − Expenses
"""

income = 5000
expenses = 2200
Savings =(income - expenses)
print=(savings)

"""16. Largest of 2 Numbers"""

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

if a > b:
    print("Largest =", a)
else:
    print("Largest =", b)

"""17. Largest of 3 Numbers"""

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

if a > b and a > c:
    print("Largest =", a)
elif b > c:
    print("Largest =", b)
else:
    print("Largest =", c)

"""18. Smallest of 3 Numbers"""

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

if a < b and a < c:
    print("Smallest =", a)
elif b < c:
    print("Smallest =", b)
else:
    print("Smallest =", c)

"""19. Leap Year"""

year = int(input("Enter year: "))

if year % 4 == 0:
    print("Leap Year")
else:
    print("Not a Leap Year")

"""20. Voting Eligibility"""

age = int(input("Enter age: "))

if age >= 18:
    print("Eligible for Voting")
else:
    print("Not Eligible for Voting")

"""21. Grade Calculator"""

marks = int(input("Enter marks: "))

if marks >= 90:
    print("Grade A")
elif marks >= 75:
    print("Grade B")
elif marks >= 50:
    print("Grade C")
else:
    print("Fail")

"""22. Profit or Loss"""

cp = float(input("Enter Cost Price: "))
sp = float(input("Enter Selling Price: "))

if sp > cp:
    print("Profit =", sp - cp)
elif cp > sp:
    print("Loss =", cp - sp)
else:
    print("No Profit No Loss")

"""23. ATM Withdrawal Validation"""

balance = float(input("Enter Balance: "))
amount = float(input("Enter Withdrawal Amount: "))

if amount <= balance:
    print("Withdrawal Successful")
else:
    print("Insufficient Balance")

"""24. Electricity Bill"""

units = int(input("Enter Units Consumed: "))

if units <= 100:
    bill = units * 2
elif units <= 200:
    bill = units * 3
else:
    bill = units * 5

print("Bill Amount =", bill)

"""25. Divisible by 5 and 11"""

num = int(input("Enter a number: "))

if num % 5 == 0 and num % 11 == 0:
    print("Divisible by 5 and 11")
else:
    print("Not Divisible by 5 and 11")

"""26. Vowel or Consonant"""

ch = input("Enter a character: ")

if ch in "aeiouAEIOU":
    print("Vowel")
else:
    print("Consonant")

"""27. Pass or Fail"""

marks = int(input("Enter marks: "))

if marks >= 35:
    print("Pass")
else:
    print("Fail")

"""28. Age Category (Child, Adult, Senior Citizen)"""

age = int(input("Enter age: "))

if age < 18:
    print("Child")
elif age < 60:
    print("Adult")
else:
    print("Senior Citizen")